DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dami_auth') THEN
        CREATE SCHEMA dami_auth;
    END IF;
END $EF$;
CREATE TABLE IF NOT EXISTS dami_auth."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
        IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'dami_auth') THEN
            CREATE SCHEMA dami_auth;
        END IF;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."AspNetRoles" (
        "Id" uuid NOT NULL,
        "Name" character varying(256),
        "NormalizedName" character varying(256),
        "ConcurrencyStamp" text,
        CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."AspNetUsers" (
        "Id" uuid NOT NULL,
        "UserName" character varying(256),
        "NormalizedUserName" character varying(256),
        "Email" character varying(256),
        "NormalizedEmail" character varying(256),
        "EmailConfirmed" boolean NOT NULL,
        "PasswordHash" text,
        "SecurityStamp" text,
        "ConcurrencyStamp" text,
        "PhoneNumber" text,
        "PhoneNumberConfirmed" boolean NOT NULL,
        "TwoFactorEnabled" boolean NOT NULL,
        "LockoutEnd" timestamp with time zone,
        "LockoutEnabled" boolean NOT NULL,
        "AccessFailedCount" integer NOT NULL,
        CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."OpenIddictApplications" (
        "Id" text NOT NULL,
        "ApplicationType" character varying(50),
        "ClientId" character varying(100),
        "ClientSecret" text,
        "ClientType" character varying(50),
        "ConcurrencyToken" character varying(50),
        "ConsentType" character varying(50),
        "DisplayName" text,
        "DisplayNames" text,
        "JsonWebKeySet" text,
        "Permissions" text,
        "PostLogoutRedirectUris" text,
        "Properties" text,
        "RedirectUris" text,
        "Requirements" text,
        "Settings" text,
        CONSTRAINT "PK_OpenIddictApplications" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."OpenIddictScopes" (
        "Id" text NOT NULL,
        "ConcurrencyToken" character varying(50),
        "Description" text,
        "Descriptions" text,
        "DisplayName" text,
        "DisplayNames" text,
        "Name" character varying(200),
        "Properties" text,
        "Resources" text,
        CONSTRAINT "PK_OpenIddictScopes" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."AspNetRoleClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "RoleId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dami_auth."AspNetRoles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."AspNetUserClaims" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "UserId" uuid NOT NULL,
        "ClaimType" text,
        "ClaimValue" text,
        CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dami_auth."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."AspNetUserLogins" (
        "LoginProvider" text NOT NULL,
        "ProviderKey" text NOT NULL,
        "ProviderDisplayName" text,
        "UserId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
        CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dami_auth."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."AspNetUserRoles" (
        "UserId" uuid NOT NULL,
        "RoleId" uuid NOT NULL,
        CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
        CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES dami_auth."AspNetRoles" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dami_auth."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."AspNetUserTokens" (
        "UserId" uuid NOT NULL,
        "LoginProvider" text NOT NULL,
        "Name" text NOT NULL,
        "Value" text,
        CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
        CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES dami_auth."AspNetUsers" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."OpenIddictAuthorizations" (
        "Id" text NOT NULL,
        "ApplicationId" text,
        "ConcurrencyToken" character varying(50),
        "CreationDate" timestamp with time zone,
        "Properties" text,
        "Scopes" text,
        "Status" character varying(50),
        "Subject" character varying(400),
        "Type" character varying(50),
        CONSTRAINT "PK_OpenIddictAuthorizations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OpenIddictAuthorizations_OpenIddictApplications_Application~" FOREIGN KEY ("ApplicationId") REFERENCES dami_auth."OpenIddictApplications" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE TABLE dami_auth."OpenIddictTokens" (
        "Id" text NOT NULL,
        "ApplicationId" text,
        "AuthorizationId" text,
        "ConcurrencyToken" character varying(50),
        "CreationDate" timestamp with time zone,
        "ExpirationDate" timestamp with time zone,
        "Payload" text,
        "Properties" text,
        "RedemptionDate" timestamp with time zone,
        "ReferenceId" character varying(100),
        "Status" character varying(50),
        "Subject" character varying(400),
        "Type" character varying(150),
        CONSTRAINT "PK_OpenIddictTokens" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_OpenIddictTokens_OpenIddictApplications_ApplicationId" FOREIGN KEY ("ApplicationId") REFERENCES dami_auth."OpenIddictApplications" ("Id"),
        CONSTRAINT "FK_OpenIddictTokens_OpenIddictAuthorizations_AuthorizationId" FOREIGN KEY ("AuthorizationId") REFERENCES dami_auth."OpenIddictAuthorizations" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON dami_auth."AspNetRoleClaims" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON dami_auth."AspNetRoles" ("NormalizedName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE INDEX "IX_AspNetUserClaims_UserId" ON dami_auth."AspNetUserClaims" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE INDEX "IX_AspNetUserLogins_UserId" ON dami_auth."AspNetUserLogins" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE INDEX "IX_AspNetUserRoles_RoleId" ON dami_auth."AspNetUserRoles" ("RoleId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE INDEX "EmailIndex" ON dami_auth."AspNetUsers" ("NormalizedEmail");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON dami_auth."AspNetUsers" ("NormalizedUserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE UNIQUE INDEX "IX_OpenIddictApplications_ClientId" ON dami_auth."OpenIddictApplications" ("ClientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE INDEX "IX_OpenIddictAuthorizations_ApplicationId_Status_Subject_Type" ON dami_auth."OpenIddictAuthorizations" ("ApplicationId", "Status", "Subject", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE UNIQUE INDEX "IX_OpenIddictScopes_Name" ON dami_auth."OpenIddictScopes" ("Name");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE INDEX "IX_OpenIddictTokens_ApplicationId_Status_Subject_Type" ON dami_auth."OpenIddictTokens" ("ApplicationId", "Status", "Subject", "Type");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE INDEX "IX_OpenIddictTokens_AuthorizationId" ON dami_auth."OpenIddictTokens" ("AuthorizationId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    CREATE UNIQUE INDEX "IX_OpenIddictTokens_ReferenceId" ON dami_auth."OpenIddictTokens" ("ReferenceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM dami_auth."__EFMigrationsHistory" WHERE "MigrationId" = '20260825001405_AuthFoundation') THEN
    INSERT INTO dami_auth."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260825001405_AuthFoundation', '10.0.11');
    END IF;
END $EF$;

grant usage on schema dami_auth to dami_app;
grant select, insert, update, delete on all tables in schema dami_auth to dami_app;
revoke truncate, references, trigger on all tables in schema dami_auth from dami_app;
